### ISSUE TITLE
Sysinfo error

### ISSUE THREAD

**Issue by devillD** [CoolFool/Ravager#7]
"2022-05-29 14:17:04,440 — telegram.ext.dispatcher — ERROR — process_update:573 — An uncaught error was raised while handling the error."
Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/telegram/ext/conversationhandler.py", line 626, in handle_update
    new_state = handler.handle_update(update, dispatcher, check_result, context)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "/app/ravager/bot/commands/admin_interface.py", line 204, in system_options
    text = sys_info_text.format(cpu_percent, used_mem.size, used_mem.suffix, available_mem.size, available_mem.suffix,
AttributeError: 'humanized' object has no attribute 'suffix'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/telegram/ext/dispatcher.py", line 567, in process_update
    self.dispatch_error(update, exc)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/telegram/ext/dispatcher.py", line 810, in dispatch_error
    callback(update, context)
  File "/app/ravager/bot/commands/error.py", line 8, in error_handler
    update.message.reply_text(quote=True, text="Error Occurred while handling request")
AttributeError: 'NoneType' object has no attribute 'reply_text'

**Comment by CoolFool** [comment]
should be fixed know

**Comment by Topkek6969** [comment]
> should be fixed know

I can verify it's fixed, you can close this issue.
